spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/misterworld}
    username: ${DB_USERNAME:misterworld}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
